import type { Lead, Activity } from "@/types";

export const mockLeads: Lead[] = [
  {
    id: "lead_001",
    name: "Sarah Chen",
    email: "sarah.chen@techcorp.io",
    budget: 25000,
    message: "We need a complete redesign of our SaaS dashboard. Looking for modern, clean aesthetics with a focus on data visualization. Our current platform serves 50K+ users.",
    status: "new",
    createdAt: "2026-07-25T06:30:00Z",
    source: "Website",
    company: "TechCorp",
  },
  {
    id: "lead_002",
    name: "Marcus Johnson",
    email: "marcus@elevatebrands.com",
    budget: 15000,
    message: "Interested in a landing page for our new product launch. We want something that converts well and looks premium. Timeline is 3 weeks.",
    status: "contacted",
    createdAt: "2026-07-24T14:20:00Z",
    source: "Referral",
    company: "Elevate Brands",
  },
  {
    id: "lead_003",
    name: "Emily Rodriguez",
    email: "emily@startupflow.co",
    budget: 8000,
    message: "Looking for a developer to build our MVP landing page. We're a B2B fintech startup. Need forms, pricing page, and integrations.",
    status: "new",
    createdAt: "2026-07-24T09:15:00Z",
    source: "Google",
    company: "StartupFlow",
  },
  {
    id: "lead_004",
    name: "David Kim",
    email: "d.kim@nexusdesign.studio",
    budget: 45000,
    message: "Enterprise project: rebuild our customer portal. Must support multi-tenant architecture. Need admin dashboard, client-facing portal, and analytics.",
    status: "contacted",
    createdAt: "2026-07-23T16:45:00Z",
    source: "LinkedIn",
    company: "Nexus Design Studio",
  },
  {
    id: "lead_005",
    name: "Jessica Patel",
    email: "jessica@greenleaf.eco",
    budget: 12000,
    message: "E-commerce redesign for our sustainable products brand. Need better product pages, checkout flow, and subscription management.",
    status: "closed",
    createdAt: "2026-07-23T11:00:00Z",
    source: "Website",
    company: "GreenLeaf",
  },
  {
    id: "lead_006",
    name: "Alex Thompson",
    email: "alex.t@cloudpeak.dev",
    budget: 35000,
    message: "Need a complete design system for our developer tools platform. Should include component library, documentation site, and playground.",
    status: "new",
    createdAt: "2026-07-22T08:30:00Z",
    source: "Twitter",
    company: "CloudPeak",
  },
  {
    id: "lead_007",
    name: "Mia Nakamura",
    email: "mia@artisanai.com",
    budget: 20000,
    message: "AI-powered content platform needs a fresh UI. Current interface is outdated. Users complain about complexity. Need intuitive onboarding flow.",
    status: "contacted",
    createdAt: "2026-07-21T13:20:00Z",
    source: "Referral",
    company: "Artisan AI",
  },
  {
    id: "lead_008",
    name: "Ryan Foster",
    email: "ryan@velocitylabs.io",
    budget: 55000,
    message: "Looking for a team to build our analytics dashboard from scratch. Real-time data, interactive charts, customizable widgets. Enterprise-grade.",
    status: "new",
    createdAt: "2026-07-21T10:00:00Z",
    source: "Website",
    company: "Velocity Labs",
  },
  {
    id: "lead_009",
    name: "Olivia Martinez",
    email: "olivia@bloomhealth.co",
    budget: 18000,
    message: "Healthcare appointment platform redesign. Must be HIPAA-compliant. Need patient portal, doctor scheduling, and telemedicine integration.",
    status: "closed",
    createdAt: "2026-07-20T15:45:00Z",
    source: "Google",
    company: "Bloom Health",
  },
  {
    id: "lead_010",
    name: "James Wilson",
    email: "james@quantumfinance.com",
    budget: 40000,
    message: "Fintech dashboard for portfolio management. Need real-time stock charts, portfolio analytics, and transaction history. Dark mode is a must.",
    status: "contacted",
    createdAt: "2026-07-20T09:30:00Z",
    source: "LinkedIn",
    company: "Quantum Finance",
  },
  {
    id: "lead_011",
    name: "Sophia Lee",
    email: "sophia@creativepulse.agency",
    budget: 10000,
    message: "Agency website redesign. We want something bold and creative that showcases our portfolio. Must have smooth animations and transitions.",
    status: "new",
    createdAt: "2026-07-19T14:00:00Z",
    source: "Website",
    company: "Creative Pulse",
  },
  {
    id: "lead_012",
    name: "Daniel Brown",
    email: "daniel@swiftlogistics.com",
    budget: 30000,
    message: "Logistics tracking platform. Real-time shipment tracking, driver management, route optimization dashboard. Mobile-responsive required.",
    status: "closed",
    createdAt: "2026-07-19T11:15:00Z",
    source: "Referral",
    company: "Swift Logistics",
  },
  {
    id: "lead_013",
    name: "Isabella Garcia",
    email: "isabella@luminary.edu",
    budget: 22000,
    message: "EdTech platform UI/UX overhaul. Student dashboard, course management, progress tracking, and gamification elements needed.",
    status: "new",
    createdAt: "2026-07-18T16:30:00Z",
    source: "Google",
    company: "Luminary Education",
  },
  {
    id: "lead_014",
    name: "Ethan Davis",
    email: "ethan@novacloud.systems",
    budget: 60000,
    message: "Cloud infrastructure management console. Server monitoring, deployment pipelines, cost analytics. Similar complexity to AWS Console but better UX.",
    status: "contacted",
    createdAt: "2026-07-18T08:00:00Z",
    source: "LinkedIn",
    company: "Nova Cloud",
  },
  {
    id: "lead_015",
    name: "Ava Mitchell",
    email: "ava@petalbeauty.com",
    budget: 14000,
    message: "Beauty brand e-commerce site. Clean, minimal aesthetic. Product showcase, ingredient transparency, subscription boxes, and loyalty program.",
    status: "new",
    createdAt: "2026-07-17T12:45:00Z",
    source: "Instagram",
    company: "Petal Beauty",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "act_001",
    type: "lead_created",
    leadName: "Sarah Chen",
    description: "submitted a new inquiry",
    timestamp: "2026-07-25T06:30:00Z",
  },
  {
    id: "act_002",
    type: "status_changed",
    leadName: "Marcus Johnson",
    description: "was moved to Contacted",
    timestamp: "2026-07-24T16:00:00Z",
  },
  {
    id: "act_003",
    type: "lead_created",
    leadName: "Emily Rodriguez",
    description: "submitted a new inquiry",
    timestamp: "2026-07-24T09:15:00Z",
  },
  {
    id: "act_004",
    type: "lead_contacted",
    leadName: "David Kim",
    description: "was contacted via email",
    timestamp: "2026-07-23T18:00:00Z",
  },
  {
    id: "act_005",
    type: "status_changed",
    leadName: "Jessica Patel",
    description: "was moved to Closed",
    timestamp: "2026-07-23T14:30:00Z",
  },
  {
    id: "act_006",
    type: "lead_created",
    leadName: "Alex Thompson",
    description: "submitted a new inquiry",
    timestamp: "2026-07-22T08:30:00Z",
  },
  {
    id: "act_007",
    type: "status_changed",
    leadName: "Mia Nakamura",
    description: "was moved to Contacted",
    timestamp: "2026-07-21T15:00:00Z",
  },
  {
    id: "act_008",
    type: "lead_created",
    leadName: "Ryan Foster",
    description: "submitted a new inquiry",
    timestamp: "2026-07-21T10:00:00Z",
  },
];
